zpb_admin_mediatek_homepage:
    path:     /{page}
    defaults: { _controller: ZPBAdminMediatekBundle:Image:index, page: 1 }
    methods: ["GET"]
    requirements:
        page: \d+

zpb_admin_mediatek_new:
    path:     /upload
    defaults: { _controller: ZPBAdminMediatekBundle:Image:new}
    methods: ["GET", "POST"]
