parameters:
#    zpb_admin_zoo.example.class: ZPB\Admin\ZooBundle\Example

services:
#    zpb_admin_zoo.example:
#        class: %zpb_admin_zoo.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
