zpb_admin_blog_article_new:
    path: /rediger
    defaults: { _controller: ZPBAdminBlogBundle:Article:new }
    methods: ["GET", "POST"]

zpb_admin_blog_article_set_published:
    path: /publier/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Article:setPublished }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_article_set_front_zoo:
    path: /mettre-a-la-une-zoo/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Article:setFrontZoo }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_article_set_front_bn:
    path: /mettre-a-la-une-beauval-nature/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Article:setFrontBn }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_article_unset_front_zoo:
    path: /retirer-de-la-une-zoo/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Article:unsetFrontZoo }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_article_unset_front_bn:
    path: /retirer-de-la-une-beauval-nature/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Article:unsetFrontBn }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_article_set_archived:
    path: /archiver/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Article:setArchived }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_article_unset_archived:
    path: /republier/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Article:unsetArchived }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_article_archives:
    path: /archives/{page}
    defaults: { _controller: ZPBAdminBlogBundle:Article:archives, page: 1}
    methods: ["GET"]
    requirements:
        page: \d+

zpb_admin_blog_article_trashes:
    path: /corbeille/{page}
    defaults: { _controller: ZPBAdminBlogBundle:Article:trashes, page: 1}
    methods: ["GET"]
    requirements:
        page: \d+

zpb_admin_blog_article_set_dropped:
    path: /mettre-a-la-corbeille/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Article:drop }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_article_set_undropped:
    path: /sortie-de-la-corbeille/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Article:undrop }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_article_delete:
    path: /supprimer/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Article:delete }
    methods: ["GET"]
    requirements:
        id: \d+
