zpb_admin_blog_category_homepage:
    path: /
    defaults: { _controller: ZPBAdminBlogBundle:Category:index }
    methods: ["GET"]

zpb_admin_blog_category_new:
    path: /nouvelle
    defaults: { _controller: ZPBAdminBlogBundle:Category:new }
    methods: ["GET", "POST"]

zpb_admin_blog_category_delete:
    path: /supprimer/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Category:delete }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_category_edit:
    path: /mise-a-jour/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Category:edit }
    methods: ["GET", "POST"]
    requirements:
        id: \d+

zpb_admin_blog_category_setDefault:
    path: /mettre-en-defaut/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Category:setDefault }
    methods: ["GET"]
    requirements:
        id: \d+
