zpb_admin_blog_tag_homepage:
    path: /
    defaults: { _controller: ZPBAdminBlogBundle:Tag:index }
    methods: ["GET"]

zpb_admin_blog_tag_new:
    path: /nouveau
    defaults: { _controller: ZPBAdminBlogBundle:Tag:new }
    methods: ["GET", "POST"]

zpb_admin_blog_tag_delete:
    path: /supprimer/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Tag:delete }
    methods: ["GET"]
    requirements:
        id: \d+

zpb_admin_blog_tag_edit:
    path: /mise-a-jour/{id}
    defaults: { _controller: ZPBAdminBlogBundle:Tag:edit }
    methods: ["GET", "POST"]
    requirements:
        id: \d+
