<?php

namespace ZPB\Admin\SponsorshipBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SponsorshipRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SponsorshipRepository extends EntityRepository
{
}
