<?php

namespace ZPB\Admin\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * EmailRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmailRepository extends EntityRepository
{
    public function setDefault(Email $email, User $user)
    {
        $emails = $user->getEmails();
        foreach($emails as $e){
            if($e->getIsDefault()){
                $e->setIsDefault(false);

                $this->_em->persist($e);
            }
        }
        $email->setIsDefault(true);
        $this->_em->persist($email);
        $user->setPrimaryEmail($email->getName());
        $this->_em->persist($user);
        $this->_em->flush();
    }
}
