<?php

namespace ZPB\Admin\CommonBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PhoneNumberRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PhoneNumberRepository extends EntityRepository
{
    public function setDefault(PhoneNumber $phone, User $user)
    {
        $phones = $user->getPhones();
        foreach($phones as $p){
            if($p->getIsDefault()){
                $p->setIsDefault(false);

                $this->_em->persist($p);
            }
        }
        $phone->setIsDefault(true);
        $this->_em->persist($phone);
        $user->setPrimaryPhone($phone->getNumber());
        $this->_em->persist($user);
        $this->_em->flush();
    }
}
