zpb_admin_common_login:
    path: /login
    defaults: { _controller: ZPBAdminCommonBundle:Security:login }
    methods: ["GET"]

zpb_admin_common_login_check:
    path: /login_check
    methods: ["POST"]

zpb_admin_common_logout:
    path: /logout
    methods: ["GET"]

zpb_admin_common_security_my_account:
    path: /utilisateur/mon-compte/{canonic}
    defaults: { _controller: ZPBAdminCommonBundle:Security:myAccount }
    methods: ["GET"]
    requirements:
        canonic: "^[a-zA-Z0-9_-]+$"
