security:
    encoders:
        ZPB\Admin\CommonBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: true
            iterations: 7000
        ZPB\Admin\SponsorshipBundle\Entity\Godparent:
            algorithm: sha512
            encode_as_base64: true
            iterations: 7000
    providers:
        admin_provider:
            entity:
                class: ZPBAdminCommonBundle:User
                #property: username
        sponsorship_provider:
            entity:
                class: ZPBAdminSponsorshipBundle:Godparent
                property: username

    role_hierarchy:
        ROLE_GODPARENT: ROLE_USER
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPERADMIN: [ROLE_USER, ROLE_ADMIN]

    access_control:
        #- { host: ^(new\.|www\.)?admin\.zooparc\.com$, path: ^/, requires_channel: https, roles: [IS_AUTHENTICATED_ANONYMOUSLY]}
        #- { host: ^(new\.|www\.)?admin\.zooparc\.com$, path: ^/, requires_channel: https, roles: [ROLE_USER]}
        - { host: ^(new\.|www\.)admin\.zooparc\.com$, path: ^/utilisateurs, requires_channel: https, roles: ROLE_SUPERADMIN }
        - { host: ^(new\.|www\.)admin\.zooparc\.com$, path: ^/utilisateur/.+, requires_channel: https, roles: ROLE_SUPERADMIN }
        - { host: ^(new\.|www\.)admin\.zooparc\.com$, path: ^/(?!(login|login_check|logout)/?$), requires_channel: https, roles: ROLE_USER }

        - { host: ^(new\.|www\.)zoobeauval\.com$, path: ^/parrainage/mon-compte, requires_channel: https, roles: ROLE_GODPARENT }

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        admin:
            host: ^(new\.|www\.)admin\.zooparc\.com$
            pattern: ^/
            security: true
            provider: admin_provider
            access_denied_url: /
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
                csrf_provider: form.csrf_provider
            logout:
                path: /logout
                target: /

        sponsorship:
            host: ^(new\.|www\.)zoobeauval\.com$
            pattern: ^/parrainage
            security: true
            provider: sponsorship_provider
            access_denied_url: /
            anonymous: ~
            form_login:
                login_path: /parrainage/login
                check_path: /parrainage/login_check
                csrf_provider: form.csrf_provider
            logout:
                path: /parrainage/logout
                target: /

        default:
            anonymous: ~
