parameters:
    default_subdommain: "new."
    mediatek_root_dir: "%kernel.root_dir%/../web"
    mediatek_uploads_img_dir: "uploads/medias/img"
    mediatek_uploads_img_thumbs_dir: "uploads/medias/thumbs"
    mediatek_uploads_pdf_dir: "uploads/medias/pdf"
    mediatek_thumb_max_size: 300















