parameters:
   mediatek_root_dir: "%kernel.root_dir%/../web"
   mediatek_uploads_img_dir: "uploads/medias/img"
   mediatek_uploads_img_thumbs_dir: "uploads/medias/thumbs"

   mediatek_thumb_max_size: 300
