<?php

namespace ZPB\Admin\ZooBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FCategoryRepository extends EntityRepository
{
    public function countCategories()
    {
        return $this->createQueryBuilder('c')->select('COUNT(c)')->getQuery()->getSingleScalarResult();
    }

    public function findAllAlphaOrdered()
    {
        $qb = $this->createQueryBuilder('c')->orderBy('c.name', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
