<?php

namespace ZPB\Admin\ZooBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * FCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FCategoryRepository extends EntityRepository
{
}
