<?php

namespace ZPB\Admin\ZooBundle\Entity;


use Gedmo\Sortable\Entity\Repository\SortableRepository;

/**
 * FImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FImageRepository extends SortableRepository
{

}
