<?php

namespace ZPB\Admin\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends EntityRepository
{
    public function countCategories()
    {
        return $this->createQueryBuilder('c')->select('COUNT(c)')->getQuery()->getSingleScalarResult();
    }

    public function findAllAlphaOrdered()
    {
        $qb = $this->createQueryBuilder("c")->orderBy("c.name", "ASC");
        return $qb->getQuery()->getResult();
    }
}
