zpb_admin_blog_homepage:
    path:     /{page}
    defaults: { _controller: ZPBAdminBlogBundle:Default:index, page: 1 }
    requirements:
        page: \d+

zpb_admin_blog_article_routes:
    prefix: /article
    resource: "@ZPBAdminBlogBundle/Resources/config/routing/article.yml"

zpb_admin_blog_category_routes:
    prefix: /categorie
    resource: "@ZPBAdminBlogBundle/Resources/config/routing/category.yml"

zpb_admin_blog_tag_routes:
    prefix: /mots-cles
    resource: "@ZPBAdminBlogBundle/Resources/config/routing/tag.yml"
