parameters:
#    zpb_admin_blog.example.class: ZPB\Admin\BlogBundle\Example

services:
#    zpb_admin_blog.example:
#        class: %zpb_admin_blog.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
