zpb_sites_zoo_parrainage_homepage:
    path: /
    defaults: { _controller: ZPBSitesZooBundle:Parrainage:index }
    methods: ["GET"]

zpb_sites_zoo_parrainage_show_animal:
    path: /voir/{name}
    defaults: { _controller: ZPBSitesZooBundle:Parrainage:showAnimal }
    methods: ["GET"]
    requirements:
        name: "[a-zA-Z0-9_-]+"

zpb_sites_zoo_parrainage_add_to_basket:
    path: /ajouter-au-panier
    defaults: { _controller: ZPBSitesZooBundle:Parrainage:addSponsorshipToBasket }
    methods: ["POST"]

zpb_sites_zoo_parrainage_remove_from_basket:
    path: /supprimer-du-panier/{id}
    defaults: { _controller: ZPBSitesZooBundle:Parrainage:removeSponsorshipToBasket }
    methods: ["GET"]
    requirements:
        id: "[0-9-]+"

zpb_sites_zoo_parrainage_payment_login_register:
    path: /identification
    defaults: { _controller: ZPBSitesZooBundle:Parrainage:loginOrRegister }
    methods: ["GET"]

zpb_sites_zoo_parrainage_show_basket:
    path: /mon-panier
    defaults: { _controller: ZPBSitesZooBundle:Parrainage:showSponsorshipToBasket }
    methods: ["GET"]

zpb_sites_zoo_parrainage_login:
    path: /login
    defaults: { _controller: ZPBSitesZooBundle:Parrainage:login }
    methods: ["GET"]

zpb_sites_zoo_parrainage_login_check:
    path: /login_check
    methods: ["POST"]

zpb_sites_zoo_parrainage_logout:
    path: /logout
    methods: ["GET"]

zpb_sites_zoo_parrainage_my_account:
    path: /mon-compte
    defaults: { _controller: ZPBSitesZooBundle:Parrainage:myAccount }
    methods: ["GET"]

zpb_sites_zoo_parrainage_my_account_animals:
    path: /mon-compte/{canonic}/mes-parrainages
    defaults: { _controller: ZPBSitesZooBundle:Parrainage:myAnimals }
    methods: ["GET"]
    requirements:
        canonic: "[a-zA-Z0-9_-]+"




