<?php

namespace ZPB\Admin\MediatekBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends EntityRepository
{
    public function countTags()
    {
        return $this->createQueryBuilder('t')->select('COUNT(t)')->getQuery()->getSingleScalarResult();
    }

    public function findAllAlphaOrdered()
    {
        $qb = $this->createQueryBuilder('t')->orderBy('t.name', 'ASC');
        return $qb->getQuery()->getResult();
    }

    public function findAllNamesAlphaOrdered()
    {
        $qb = $this->createQueryBuilder('t')->select('t.name')->orderBy('t.name', 'ASC');
        return $qb->getQuery()->getArrayResult();
    }
}
