zpb_admin_common_homepage:
    path:     /
    defaults: { _controller: ZPBAdminCommonBundle:Default:index }
    methods: ["GET"]

zpb_admin_common_security_routes:
    resource: "@ZPBAdminCommonBundle/Resources/config/routing/security.yml"

zpb_admin_common_security_phone_routes:
    resource: "@ZPBAdminCommonBundle/Resources/config/routing/phone.yml"

zpb_admin_common_security_email_routes:
    resource: "@ZPBAdminCommonBundle/Resources/config/routing/email.yml"
