zpb_admin_common_homepage:
    path:     /
    defaults: { _controller: ZPBAdminCommonBundle:Default:index }
    methods: ["GET"]

zpb_admin_common_login:
    path: /login
    defaults: { _controller: ZPBAdminCommonBundle:Security:login }
    methods: ["GET"]

zpb_admin_common_login_check:
    path: /login_check
    methods: ["POST"]

zpb_admin_common_logout:
    path: /logout
    methods: ["GET"]
