zpb_admin_zoo_fototek_homepage:
    path: /image/{page}
    defaults: { _controller: ZPBAdminZooBundle:Fototek:index, page: 1 }
    methods: ["GET"]
    requirements:
        page: \d+

zpb_admin_zoo_fototek_image_new:
    path: /image/upload
    defaults: { _controller: ZPBAdminZooBundle:Fototek:newImage }
    methods: ["GET","POST"]
